config/routes.rb
Rails.application.routes.draw do

  # You can have the root of your site routed with "root"
  root 'polls#index'

  resources :polls do
    resources :options, except: [:destroy]do
      put 'add_vote', on: :member
    end
  end
end

app/models/controller.rb
class Controller < ActiveRecord::Base
end

app/models/option.rb
class Option < ActiveRecord::Base
  belongs_to :poll
  validates :answer, presence: true
  validates :count, presence: true
  validates :count, numericality: true
  # trivial
  def add_vote!
    self.count = self.count + 1
    save
  end

end

app/models/poll.rb
class Poll < ActiveRecord::Base

  has_many :options

  # took this code from mae and sebatians code
  accepts_nested_attributes_for :options, allow_destroy: true,
                                reject_if: lambda { |option| option['answer'].blank? }
  validates :owner, presence: true
  validates :question, presence: true

  def old
    self.created_at + (7*24*60*60) < DateTime.now
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/options_controller.rb
class OptionsController < ApplicationController
  before_action :set_poll
  before_action :set_option, only: [:show, :edit, :add_vote]

  def add_vote
    session[:voted] ||=[]
    if session[:voted].include?(@poll.id)
       redirect_to @poll
    else
      @option.add_vote!
      session[:voted] << @poll.id
      redirect_to @poll
    end
  end

  def index
    @options = @poll.options
  end

  def show
  end

  # GET /options/new
  def new
    @option = Option.new
  end

  # GET /options/1/edit
  def edit
  end

  def create
    @option = @poll.options.create(option_params)
      if @option.save
        redirect_to  poll_options_path, notice: 'Option was successfully created.'
      else
        render :new
      end
  end

  # PATCH/PUT /options/1
  # PATCH/PUT /options/1.json
  def update
    respond_to do |format|
      if @option.update(option_params)
        format.html { redirect_to @option, notice: 'Option was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end


  # DELETE /options/1
  # DELETE /options/1.json
  def destroy
    @option.destroy
    respond_to do |format|
      format.html { redirect_to options_url, notice: 'Option was successfully destroyed.' }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_option
      @option = @poll.options.find(params[:id])
    end

    def set_poll
      @poll = Poll.find(params[:poll_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def option_params
      params.require(:option).permit(:answer, :count)
    end
end

app/controllers/polls_controller.rb
class PollsController < ApplicationController
  before_action :set_poll, only: [:show, :edit, :update, :destroy]

  # GET /polls
  # GET /polls.json
  def index
    session[:voted] ||=[]
    @polls = Poll.all
  end

  # GET /polls/1
  # GET /polls/1.json
  def show
    @options = Option.where(id: session[:poll_id])
  end

  # GET /polls/new
  def new
    @poll = Poll.new
    @poll.options.build
    respond_to do |format|
      format.html
      format.js
    end
  end

  # GET /polls/1/edit
  def edit
  end

  # POST /polls
  # POST /polls.json
  def create
    @poll = Poll.new(poll_params)
    respond_to do |format|
      if @poll.save
        format.html { redirect_to @poll, notice: 'Poll was successfully created.' }
        format.js do
          @polls = Poll.all
        end
      else
        format.html { render :new }
        format.js { render :new }
      end
    end
  end

  # PATCH/PUT /polls/1
  # PATCH/PUT /polls/1.json
  def update
    respond_to do |format|
      if @poll.update(poll_params)
        format.html { redirect_to @poll, notice: 'Poll was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /polls/1
  # DELETE /polls/1.json
  def destroy
    @poll.destroy
    respond_to do |format|
      format.html { redirect_to polls_url, notice: 'Poll was successfully destroyed.' }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_poll
      @poll = Poll.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def poll_params
      params[:poll].permit(:owner, :question, :choices, {options_attributes: [:id, :answer,:count]})
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  # I got this code from Railscast episode 196
  def link_to_add_fields(name, f, association)
    new_object = f.object.send(association).klass.new
    id = new_object.object_id
    fields = f.fields_for(association, new_object, child_index: id) do |builder|
      render(association.to_s.singularize + "_fields", f: builder)
    end
    link_to(name, '#', class: "add_fields", data: {id: id, fields: fields.gsub("\n", "")})
  end
end

app/helpers/options_helper.rb
module OptionsHelper
end

app/helpers/polls_helper.rb
module PollsHelper
  def recent
    5.times do

    end
  end
end

app/views/application/_topbar.html.erb
<nav class="top-bar" data-topbar>
    <ul class="title-area">
      <li class="name">
        <h1><%= link_to 'Pollish', root_path %></h1>
      </li>
      <!-- Remove the class "menu-icon" to get rid of menu icon. Take out "Menu" to just have icon alone -->
      <li class="toggle-topbar menu-icon"><a href="#"><span>Menu</span></a></li>
    </ul>

    <section class="top-bar-section">
      <!-- Left Nav Section -->
      <ul class="left">
        <li><%= link_to "Polls", polls_path %></li>
      </ul>
    </section>
  </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <% content_for :title, "Pollish" %>
    <link href='http://fonts.googleapis.com/css?family=Pacifico|Signika:600' rel='stylesheet' type='text/css'>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <%= javascript_include_tag "//www.google.com/jsapi", "chartkick" %>
    <title><%= content_for?(:title) ? yield(:title) : "Pollish" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <%= render 'topbar' %>
    <div class="container">
    <%= yield %>
    <%= javascript_include_tag "application" %>
    </div>
  </body>

</html>

app/views/options/_form.html.erb
<%= simple_form_for([@poll, @option]) do |o| %>

    <%= o.error_notification %>
    <%= o.input :answer, label: "Option" %>
    <%= o.input :count, :as => "hidden", :input_html => { :value => 0 } %>
    <%= o.button :submit %>

<% end %>

app/views/polls/_form.html.erb
<%= form_for(@poll) do |f| %>
    <% if @poll.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@poll.errors.count, "error") %> prohibited this poll from being saved:</h2>

          <ul>
            <% @poll.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="field">
      <%= f.label :owner %><br>
      <%= f.text_field :owner %>
    </div>

    <div class="field">
      <%= f.label :question %><br>
      <%= f.text_field :question %>
    </div>

    <div>
      <%= f.fields_for :options do |b| %>
         <%= render 'option_fields', f: b %>
    <% end %>
      <%= link_to_add_fields "Add another option", f, :options %>
    </div><br>

    <div class="actions">
      <%= f.submit %>
    </div>
<% end %>

app/views/polls/_option_fields.html.erb
<fieldset>
  <%= f.hidden_field :count, value: 0 %>
  <%= f.label :answer, "Answer" %>
  <%= f.text_field :answer %>
  <%= f.hidden_field :_destroy %>
  <%= link_to "remove", '#', class: "remove_fields" %>
</fieldset>

app/views/polls/_poll.html.erb
  <% @polls.each do |poll| %>
  <%if poll.old == false %>
      <tr>
        <td><%= sanitize poll.owner.capitalize %></td>
        <td><%= sanitize link_to poll.question, poll %></td>
      </tr>
  <% end %>
  <% end %>

app/views/polls/_polls.html.erb
<table>
  <thead>
  <tr>
    <th>Owner</th>
    <th>Question</th>
  </tr>
  </thead>
  <tbody>
<%= render 'poll' %>
  </tbody>
</table>

app/views/polls/create.js.erb
$("#new-poll-modal").
    html('').
    foundation("reveal", "close");

//code to update the page
$("#polls").html('<%= j render(:partial => "polls", :object => @polls) %>');

app/views/polls/edit.html.erb
<h1>Editing poll</h1>

<%= render 'form' %>

<%= link_to 'Show', @poll %> |
<%= link_to 'Back', polls_path %>

app/views/polls/index.html.erb
<h1>Poll<span class="special">ish</span></h1>

<div id="polls">
  <%= render :partial => "polls", :locals => {:polls => @polls} %>
</div>



<%= link_to 'Make your own!', new_poll_path, :class => "button [radius round]", remote: true %>
<div id="new-poll-modal" class="reveal-modal" data-reveal></div>

app/views/polls/new.html.erb
<h1 class = "special">New poll</h1>

<%= render 'form' %>
<%= link_to 'Back', polls_path %>

app/views/polls/new.js.erb
$("#new-poll-modal").
    html('<%= j render "form" %>').
    append('<a class=\"close-reveal-modal\">&#215;</a>').
    foundation("reveal", "open");

$('#new_poll').
    attr("data-remote", "true");

(function() {
  jQuery(function() {
    $('form').on('click', '.remove_fields', function(event) {
      $(this).prev('input[type=hidden]').val('1');
      $(this).closest('fieldset').fadeOut();
      return event.preventDefault();
    });
    return $('form').on('click', '.add_fields', function(event) {
      var regexp, time;
      time = new Date().getTime();
      regexp = new RegExp($(this).data('id'), 'g');
      $(this).before($(this).data('fields').replace(regexp, time));
      return event.preventDefault();
    });
  });

}).call(this);

app/views/polls/show.html.erb
<p id="notice"><%= notice %></p>
<% if !session[:voted].include?(@poll.id) %>
<h2><%= @poll.question%></h2>
<p>Created by: <%= sanitize @poll.owner%> at:<%= @poll.created_at%></p>

<% i = 1 %>
<% @poll.options.each do |option| %>
    <p>Answer <%= i %>: | <%= option.answer %> |
    <%=  link_to 'addvote', add_vote_poll_option_path(@poll, option), method: :put  %></p>
    <% i += 1 %>
<% end %>

<%= link_to 'Edit', edit_poll_path(@poll) %> |
<%= link_to 'Back', polls_path %>

 <% else # if session[:voted] %>
    <h2><%= @poll.question%></h2>
    <% @poll.options.each do |option| %>
        <p><%= sanitize option.answer %> | <%= option.count %> votes</p>
    <% end # do each %>

    <%= pie_chart @poll.options.pluck(:answer, :count) %>

<%end # if %>